# configs/constants.py
"""시뮬레이터 내 모든 수치 상수를 중앙 집중 관리합니다."""

BASE_TEMPERATURE = 25.0
MAX_HONEY_CAPACITY = 100.0
PHEROMONE_CHECK_INTERVAL = 10
MAX_AGE_DAYS = 45
QUEEN_DAILY_EGG_LIMIT = 2000
ENERGY_CONSUMPTION_RATE = 0.05